using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string CollectorLocation = @"collector_location";
        
		public static readonly string Depart = @"depart";
        
		public static readonly string Limit = @"limit";
        
		public static readonly string Project = @"project";
        
		public static readonly string ProjectTrace = @"project_trace";
        
		public static readonly string Projectclass = @"projectclass";
        
		public static readonly string Role = @"role";
        
		public static readonly string SArea = @"s_area";
        
		public static readonly string SCommunity = @"s_community";
        
		public static readonly string SStreet = @"s_street";
        
		public static readonly string SysLog = @"sys_log";
        
		public static readonly string User = @"users";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table CollectorLocation
		{
            get { return DataService.GetSchema("collector_location", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table Depart
		{
            get { return DataService.GetSchema("depart", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table Limit
		{
            get { return DataService.GetSchema("limit", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table Project
		{
            get { return DataService.GetSchema("project", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table ProjectTrace
		{
            get { return DataService.GetSchema("project_trace", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table Projectclass
		{
            get { return DataService.GetSchema("projectclass", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table Role
		{
            get { return DataService.GetSchema("role", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table SArea
		{
            get { return DataService.GetSchema("s_area", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table SCommunity
		{
            get { return DataService.GetSchema("s_community", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table SStreet
		{
            get { return DataService.GetSchema("s_street", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table SysLog
		{
            get { return DataService.GetSchema("sys_log", "Yannis_DAO"); }
		}
        
		public static TableSchema.Table User
		{
            get { return DataService.GetSchema("users", "Yannis_DAO"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["Yannis_DAO"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string Yannis_DAO = @"Yannis_DAO";
    
}
#endregion