using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for collecto_info
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CollectoInfoController
    {
        // Preload our schema..
        CollectoInfo thisSchemaLoad = new CollectoInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CollectoInfoCollection FetchAll()
        {
            CollectoInfoCollection coll = new CollectoInfoCollection();
            Query qry = new Query(CollectoInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CollectoInfoCollection FetchByID(object Id)
        {
            CollectoInfoCollection coll = new CollectoInfoCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CollectoInfoCollection FetchByQuery(Query qry)
        {
            CollectoInfoCollection coll = new CollectoInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (CollectoInfo.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (CollectoInfo.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? Collectorid,string Collectorname,string Projcode,DateTime? Adddate)
	    {
		    CollectoInfo item = new CollectoInfo();
		    
            item.Collectorid = Collectorid;
            
            item.Collectorname = Collectorname;
            
            item.Projcode = Projcode;
            
            item.Adddate = Adddate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? Collectorid,string Collectorname,string Projcode,DateTime? Adddate)
	    {
		    CollectoInfo item = new CollectoInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Collectorid = Collectorid;
				
			item.Collectorname = Collectorname;
				
			item.Projcode = Projcode;
				
			item.Adddate = Adddate;
				
	        item.Save(UserName);
	    }
    }
}
