using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for collector_location
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CollectorLocationController
    {
        // Preload our schema..
        CollectorLocation thisSchemaLoad = new CollectorLocation();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CollectorLocationCollection FetchAll()
        {
            CollectorLocationCollection coll = new CollectorLocationCollection();
            Query qry = new Query(CollectorLocation.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CollectorLocationCollection FetchByID(object Id)
        {
            CollectorLocationCollection coll = new CollectorLocationCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CollectorLocationCollection FetchByQuery(Query qry)
        {
            CollectorLocationCollection coll = new CollectorLocationCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (CollectorLocation.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (CollectorLocation.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int Id,int? Collectorid,string Longitude,string Atitude,DateTime? Localtionupdate,string Location)
	    {
		    CollectorLocation item = new CollectorLocation();
		    
            item.Id = Id;
            
            item.Collectorid = Collectorid;
            
            item.Longitude = Longitude;
            
            item.Atitude = Atitude;
            
            item.Localtionupdate = Localtionupdate;
            
            item.Location = Location;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? Collectorid,string Longitude,string Atitude,DateTime? Localtionupdate,string Location)
	    {
		    CollectorLocation item = new CollectorLocation();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Collectorid = Collectorid;
				
			item.Longitude = Longitude;
				
			item.Atitude = Atitude;
				
			item.Localtionupdate = Localtionupdate;
				
			item.Location = Location;
				
	        item.Save(UserName);
	    }
    }
}
