using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for depart_info
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DepartInfoController
    {
        // Preload our schema..
        DepartInfo thisSchemaLoad = new DepartInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DepartInfoCollection FetchAll()
        {
            DepartInfoCollection coll = new DepartInfoCollection();
            Query qry = new Query(DepartInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DepartInfoCollection FetchByID(object Id)
        {
            DepartInfoCollection coll = new DepartInfoCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DepartInfoCollection FetchByQuery(Query qry)
        {
            DepartInfoCollection coll = new DepartInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (DepartInfo.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (DepartInfo.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Projcode,string Departcode,string Departname,DateTime? Adddate)
	    {
		    DepartInfo item = new DepartInfo();
		    
            item.Projcode = Projcode;
            
            item.Departcode = Departcode;
            
            item.Departname = Departname;
            
            item.Adddate = Adddate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Projcode,string Departcode,string Departname,DateTime? Adddate)
	    {
		    DepartInfo item = new DepartInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Projcode = Projcode;
				
			item.Departcode = Departcode;
				
			item.Departname = Departname;
				
			item.Adddate = Adddate;
				
	        item.Save(UserName);
	    }
    }
}
