using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for depart
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DepartController
    {
        // Preload our schema..
        Depart thisSchemaLoad = new Depart();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DepartCollection FetchAll()
        {
            DepartCollection coll = new DepartCollection();
            Query qry = new Query(Depart.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DepartCollection FetchByID(object Id)
        {
            DepartCollection coll = new DepartCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DepartCollection FetchByQuery(Query qry)
        {
            DepartCollection coll = new DepartCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Depart.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Depart.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Departcode,string Departname,string Parentcode,int? Areacode,string Departmobile,string Departtel,int? Departstate,int? Isacceptmessage,string Mark,DateTime? Adddate,string Rolecode,bool? Isdel)
	    {
		    Depart item = new Depart();
		    
            item.Departcode = Departcode;
            
            item.Departname = Departname;
            
            item.Parentcode = Parentcode;
            
            item.Areacode = Areacode;
            
            item.Departmobile = Departmobile;
            
            item.Departtel = Departtel;
            
            item.Departstate = Departstate;
            
            item.Isacceptmessage = Isacceptmessage;
            
            item.Mark = Mark;
            
            item.Adddate = Adddate;
            
            item.Rolecode = Rolecode;
            
            item.Isdel = Isdel;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Departcode,string Departname,string Parentcode,int? Areacode,string Departmobile,string Departtel,int? Departstate,int? Isacceptmessage,string Mark,DateTime? Adddate,string Rolecode,bool? Isdel)
	    {
		    Depart item = new Depart();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Departcode = Departcode;
				
			item.Departname = Departname;
				
			item.Parentcode = Parentcode;
				
			item.Areacode = Areacode;
				
			item.Departmobile = Departmobile;
				
			item.Departtel = Departtel;
				
			item.Departstate = Departstate;
				
			item.Isacceptmessage = Isacceptmessage;
				
			item.Mark = Mark;
				
			item.Adddate = Adddate;
				
			item.Rolecode = Rolecode;
				
			item.Isdel = Isdel;
				
	        item.Save(UserName);
	    }
    }
}
