using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for info_depart
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoDepartController
    {
        // Preload our schema..
        InfoDepart thisSchemaLoad = new InfoDepart();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoDepartCollection FetchAll()
        {
            InfoDepartCollection coll = new InfoDepartCollection();
            Query qry = new Query(InfoDepart.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoDepartCollection FetchByID(object Id)
        {
            InfoDepartCollection coll = new InfoDepartCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoDepartCollection FetchByQuery(Query qry)
        {
            InfoDepartCollection coll = new InfoDepartCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InfoDepart.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InfoDepart.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Projcode,string Departcode,string Departname,DateTime? Adddate)
	    {
		    InfoDepart item = new InfoDepart();
		    
            item.Projcode = Projcode;
            
            item.Departcode = Departcode;
            
            item.Departname = Departname;
            
            item.Adddate = Adddate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Projcode,string Departcode,string Departname,DateTime? Adddate)
	    {
		    InfoDepart item = new InfoDepart();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Projcode = Projcode;
				
			item.Departcode = Departcode;
				
			item.Departname = Departname;
				
			item.Adddate = Adddate;
				
	        item.Save(UserName);
	    }
    }
}
