using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for info_area
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoAreaController
    {
        // Preload our schema..
        InfoArea thisSchemaLoad = new InfoArea();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoAreaCollection FetchAll()
        {
            InfoAreaCollection coll = new InfoAreaCollection();
            Query qry = new Query(InfoArea.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoAreaCollection FetchByID(object Id)
        {
            InfoAreaCollection coll = new InfoAreaCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoAreaCollection FetchByQuery(Query qry)
        {
            InfoAreaCollection coll = new InfoAreaCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InfoArea.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InfoArea.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Projcode,string Areacode,DateTime? Adddate,string Streetcode,string Commnuitycode,string Areaname,string Streetname,string Commnuityname)
	    {
		    InfoArea item = new InfoArea();
		    
            item.Projcode = Projcode;
            
            item.Areacode = Areacode;
            
            item.Adddate = Adddate;
            
            item.Streetcode = Streetcode;
            
            item.Commnuitycode = Commnuitycode;
            
            item.Areaname = Areaname;
            
            item.Streetname = Streetname;
            
            item.Commnuityname = Commnuityname;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Projcode,string Areacode,DateTime? Adddate,string Streetcode,string Commnuitycode,string Areaname,string Streetname,string Commnuityname)
	    {
		    InfoArea item = new InfoArea();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Projcode = Projcode;
				
			item.Areacode = Areacode;
				
			item.Adddate = Adddate;
				
			item.Streetcode = Streetcode;
				
			item.Commnuitycode = Commnuitycode;
				
			item.Areaname = Areaname;
				
			item.Streetname = Streetname;
				
			item.Commnuityname = Commnuityname;
				
	        item.Save(UserName);
	    }
    }
}
