using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for info_collector
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class InfoCollectorController
    {
        // Preload our schema..
        InfoCollector thisSchemaLoad = new InfoCollector();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public InfoCollectorCollection FetchAll()
        {
            InfoCollectorCollection coll = new InfoCollectorCollection();
            Query qry = new Query(InfoCollector.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoCollectorCollection FetchByID(object Id)
        {
            InfoCollectorCollection coll = new InfoCollectorCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public InfoCollectorCollection FetchByQuery(Query qry)
        {
            InfoCollectorCollection coll = new InfoCollectorCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (InfoCollector.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (InfoCollector.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? Collectorid,string Collectorname,string Projcode,DateTime? Adddate)
	    {
		    InfoCollector item = new InfoCollector();
		    
            item.Collectorid = Collectorid;
            
            item.Collectorname = Collectorname;
            
            item.Projcode = Projcode;
            
            item.Adddate = Adddate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? Collectorid,string Collectorname,string Projcode,DateTime? Adddate)
	    {
		    InfoCollector item = new InfoCollector();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Collectorid = Collectorid;
				
			item.Collectorname = Collectorname;
				
			item.Projcode = Projcode;
				
			item.Adddate = Adddate;
				
	        item.Save(UserName);
	    }
    }
}
