using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
	/// <summary>
	/// Strongly-typed collection for the Projectimg class.
	/// </summary>
    [Serializable]
	public partial class ProjectimgCollection : ActiveList<Projectimg, ProjectimgCollection>
	{	   
		public ProjectimgCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ProjectimgCollection</returns>
		public ProjectimgCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Projectimg o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the projectimg table.
	/// </summary>
	[Serializable]
	public partial class Projectimg : ActiveRecord<Projectimg>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Projectimg()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Projectimg(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Projectimg(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Projectimg(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("projectimg", TableType.Table, DataService.GetInstance("Yannis_DAO"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarProjcode = new TableSchema.TableColumn(schema);
				colvarProjcode.ColumnName = "projcode";
				colvarProjcode.DataType = DbType.String;
				colvarProjcode.MaxLength = 50;
				colvarProjcode.AutoIncrement = false;
				colvarProjcode.IsNullable = true;
				colvarProjcode.IsPrimaryKey = false;
				colvarProjcode.IsForeignKey = false;
				colvarProjcode.IsReadOnly = false;
				colvarProjcode.DefaultSetting = @"";
				colvarProjcode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarProjcode);
				
				TableSchema.TableColumn colvarImgurl = new TableSchema.TableColumn(schema);
				colvarImgurl.ColumnName = "imgurl";
				colvarImgurl.DataType = DbType.String;
				colvarImgurl.MaxLength = 200;
				colvarImgurl.AutoIncrement = false;
				colvarImgurl.IsNullable = true;
				colvarImgurl.IsPrimaryKey = false;
				colvarImgurl.IsForeignKey = false;
				colvarImgurl.IsReadOnly = false;
				colvarImgurl.DefaultSetting = @"";
				colvarImgurl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarImgurl);
				
				TableSchema.TableColumn colvarImgtype = new TableSchema.TableColumn(schema);
				colvarImgtype.ColumnName = "imgtype";
				colvarImgtype.DataType = DbType.Int32;
				colvarImgtype.MaxLength = 0;
				colvarImgtype.AutoIncrement = false;
				colvarImgtype.IsNullable = true;
				colvarImgtype.IsPrimaryKey = false;
				colvarImgtype.IsForeignKey = false;
				colvarImgtype.IsReadOnly = false;
				colvarImgtype.DefaultSetting = @"";
				colvarImgtype.ForeignKeyTableName = "";
				schema.Columns.Add(colvarImgtype);
				
				TableSchema.TableColumn colvarAdddate = new TableSchema.TableColumn(schema);
				colvarAdddate.ColumnName = "adddate";
				colvarAdddate.DataType = DbType.DateTime;
				colvarAdddate.MaxLength = 0;
				colvarAdddate.AutoIncrement = false;
				colvarAdddate.IsNullable = true;
				colvarAdddate.IsPrimaryKey = false;
				colvarAdddate.IsForeignKey = false;
				colvarAdddate.IsReadOnly = false;
				colvarAdddate.DefaultSetting = @"";
				colvarAdddate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAdddate);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Yannis_DAO"].AddSchema("projectimg",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Projcode")]
		[Bindable(true)]
		public string Projcode 
		{
			get { return GetColumnValue<string>(Columns.Projcode); }
			set { SetColumnValue(Columns.Projcode, value); }
		}
		  
		[XmlAttribute("Imgurl")]
		[Bindable(true)]
		public string Imgurl 
		{
			get { return GetColumnValue<string>(Columns.Imgurl); }
			set { SetColumnValue(Columns.Imgurl, value); }
		}
		  
		[XmlAttribute("Imgtype")]
		[Bindable(true)]
		public int? Imgtype 
		{
			get { return GetColumnValue<int?>(Columns.Imgtype); }
			set { SetColumnValue(Columns.Imgtype, value); }
		}
		  
		[XmlAttribute("Adddate")]
		[Bindable(true)]
		public DateTime? Adddate 
		{
			get { return GetColumnValue<DateTime?>(Columns.Adddate); }
			set { SetColumnValue(Columns.Adddate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varProjcode,string varImgurl,int? varImgtype,DateTime? varAdddate)
		{
			Projectimg item = new Projectimg();
			
			item.Projcode = varProjcode;
			
			item.Imgurl = varImgurl;
			
			item.Imgtype = varImgtype;
			
			item.Adddate = varAdddate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varProjcode,string varImgurl,int? varImgtype,DateTime? varAdddate)
		{
			Projectimg item = new Projectimg();
			
				item.Id = varId;
			
				item.Projcode = varProjcode;
			
				item.Imgurl = varImgurl;
			
				item.Imgtype = varImgtype;
			
				item.Adddate = varAdddate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ProjcodeColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ImgurlColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ImgtypeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn AdddateColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Projcode = @"projcode";
			 public static string Imgurl = @"imgurl";
			 public static string Imgtype = @"imgtype";
			 public static string Adddate = @"adddate";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
