using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
	/// <summary>
	/// Strongly-typed collection for the SysLog class.
	/// </summary>
    [Serializable]
	public partial class SysLogCollection : ActiveList<SysLog, SysLogCollection>
	{	   
		public SysLogCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SysLogCollection</returns>
		public SysLogCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SysLog o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the sys_log table.
	/// </summary>
	[Serializable]
	public partial class SysLog : ActiveRecord<SysLog>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public SysLog()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SysLog(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SysLog(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SysLog(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("sys_log", TableType.Table, DataService.GetInstance("Yannis_DAO"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarUserid = new TableSchema.TableColumn(schema);
				colvarUserid.ColumnName = "userid";
				colvarUserid.DataType = DbType.Int32;
				colvarUserid.MaxLength = 0;
				colvarUserid.AutoIncrement = false;
				colvarUserid.IsNullable = true;
				colvarUserid.IsPrimaryKey = false;
				colvarUserid.IsForeignKey = false;
				colvarUserid.IsReadOnly = false;
				colvarUserid.DefaultSetting = @"";
				colvarUserid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserid);
				
				TableSchema.TableColumn colvarLoginname = new TableSchema.TableColumn(schema);
				colvarLoginname.ColumnName = "loginname";
				colvarLoginname.DataType = DbType.String;
				colvarLoginname.MaxLength = 50;
				colvarLoginname.AutoIncrement = false;
				colvarLoginname.IsNullable = true;
				colvarLoginname.IsPrimaryKey = false;
				colvarLoginname.IsForeignKey = false;
				colvarLoginname.IsReadOnly = false;
				colvarLoginname.DefaultSetting = @"";
				colvarLoginname.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLoginname);
				
				TableSchema.TableColumn colvarIp = new TableSchema.TableColumn(schema);
				colvarIp.ColumnName = "ip";
				colvarIp.DataType = DbType.String;
				colvarIp.MaxLength = 20;
				colvarIp.AutoIncrement = false;
				colvarIp.IsNullable = true;
				colvarIp.IsPrimaryKey = false;
				colvarIp.IsForeignKey = false;
				colvarIp.IsReadOnly = false;
				colvarIp.DefaultSetting = @"";
				colvarIp.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIp);
				
				TableSchema.TableColumn colvarActionname = new TableSchema.TableColumn(schema);
				colvarActionname.ColumnName = "actionname";
				colvarActionname.DataType = DbType.String;
				colvarActionname.MaxLength = 100;
				colvarActionname.AutoIncrement = false;
				colvarActionname.IsNullable = true;
				colvarActionname.IsPrimaryKey = false;
				colvarActionname.IsForeignKey = false;
				colvarActionname.IsReadOnly = false;
				colvarActionname.DefaultSetting = @"";
				colvarActionname.ForeignKeyTableName = "";
				schema.Columns.Add(colvarActionname);
				
				TableSchema.TableColumn colvarCuDate = new TableSchema.TableColumn(schema);
				colvarCuDate.ColumnName = "cu_date";
				colvarCuDate.DataType = DbType.DateTime;
				colvarCuDate.MaxLength = 0;
				colvarCuDate.AutoIncrement = false;
				colvarCuDate.IsNullable = true;
				colvarCuDate.IsPrimaryKey = false;
				colvarCuDate.IsForeignKey = false;
				colvarCuDate.IsReadOnly = false;
				colvarCuDate.DefaultSetting = @"";
				colvarCuDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCuDate);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Yannis_DAO"].AddSchema("sys_log",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Userid")]
		[Bindable(true)]
		public int? Userid 
		{
			get { return GetColumnValue<int?>(Columns.Userid); }
			set { SetColumnValue(Columns.Userid, value); }
		}
		  
		[XmlAttribute("Loginname")]
		[Bindable(true)]
		public string Loginname 
		{
			get { return GetColumnValue<string>(Columns.Loginname); }
			set { SetColumnValue(Columns.Loginname, value); }
		}
		  
		[XmlAttribute("Ip")]
		[Bindable(true)]
		public string Ip 
		{
			get { return GetColumnValue<string>(Columns.Ip); }
			set { SetColumnValue(Columns.Ip, value); }
		}
		  
		[XmlAttribute("Actionname")]
		[Bindable(true)]
		public string Actionname 
		{
			get { return GetColumnValue<string>(Columns.Actionname); }
			set { SetColumnValue(Columns.Actionname, value); }
		}
		  
		[XmlAttribute("CuDate")]
		[Bindable(true)]
		public DateTime? CuDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.CuDate); }
			set { SetColumnValue(Columns.CuDate, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varUserid,string varLoginname,string varIp,string varActionname,DateTime? varCuDate)
		{
			SysLog item = new SysLog();
			
			item.Userid = varUserid;
			
			item.Loginname = varLoginname;
			
			item.Ip = varIp;
			
			item.Actionname = varActionname;
			
			item.CuDate = varCuDate;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,int? varUserid,string varLoginname,string varIp,string varActionname,DateTime? varCuDate)
		{
			SysLog item = new SysLog();
			
				item.Id = varId;
			
				item.Userid = varUserid;
			
				item.Loginname = varLoginname;
			
				item.Ip = varIp;
			
				item.Actionname = varActionname;
			
				item.CuDate = varCuDate;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn UseridColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn LoginnameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn IpColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn ActionnameColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CuDateColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Userid = @"userid";
			 public static string Loginname = @"loginname";
			 public static string Ip = @"ip";
			 public static string Actionname = @"actionname";
			 public static string CuDate = @"cu_date";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
