using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for projectclass
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ProjectclassController
    {
        // Preload our schema..
        Projectclass thisSchemaLoad = new Projectclass();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ProjectclassCollection FetchAll()
        {
            ProjectclassCollection coll = new ProjectclassCollection();
            Query qry = new Query(Projectclass.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProjectclassCollection FetchByID(object Id)
        {
            ProjectclassCollection coll = new ProjectclassCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProjectclassCollection FetchByQuery(Query qry)
        {
            ProjectclassCollection coll = new ProjectclassCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Projectclass.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Projectclass.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Classid,string Classname,int? Classtype,string Parentid,bool Isdel)
	    {
		    Projectclass item = new Projectclass();
		    
            item.Classid = Classid;
            
            item.Classname = Classname;
            
            item.Classtype = Classtype;
            
            item.Parentid = Parentid;
            
            item.Isdel = Isdel;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Classid,string Classname,int? Classtype,string Parentid,bool Isdel)
	    {
		    Projectclass item = new Projectclass();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Classid = Classid;
				
			item.Classname = Classname;
				
			item.Classtype = Classtype;
				
			item.Parentid = Parentid;
				
			item.Isdel = Isdel;
				
	        item.Save(UserName);
	    }
    }
}
