using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for project_trace
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ProjectTraceController
    {
        // Preload our schema..
        ProjectTrace thisSchemaLoad = new ProjectTrace();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ProjectTraceCollection FetchAll()
        {
            ProjectTraceCollection coll = new ProjectTraceCollection();
            Query qry = new Query(ProjectTrace.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProjectTraceCollection FetchByID(object Id)
        {
            ProjectTraceCollection coll = new ProjectTraceCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ProjectTraceCollection FetchByQuery(Query qry)
        {
            ProjectTraceCollection coll = new ProjectTraceCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (ProjectTrace.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (ProjectTrace.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Projcode,string Actionname,int? Operatorid,string Operatorname,DateTime? Operatordate,int? Prenodeid,int? Currentnodeid,string Opinion,int? Operatordepart,DateTime? Acceptdate)
	    {
		    ProjectTrace item = new ProjectTrace();
		    
            item.Projcode = Projcode;
            
            item.Actionname = Actionname;
            
            item.Operatorid = Operatorid;
            
            item.Operatorname = Operatorname;
            
            item.Operatordate = Operatordate;
            
            item.Prenodeid = Prenodeid;
            
            item.Currentnodeid = Currentnodeid;
            
            item.Opinion = Opinion;
            
            item.Operatordepart = Operatordepart;
            
            item.Acceptdate = Acceptdate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Projcode,string Actionname,int? Operatorid,string Operatorname,DateTime? Operatordate,int? Prenodeid,int? Currentnodeid,string Opinion,int? Operatordepart,DateTime? Acceptdate)
	    {
		    ProjectTrace item = new ProjectTrace();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Projcode = Projcode;
				
			item.Actionname = Actionname;
				
			item.Operatorid = Operatorid;
				
			item.Operatorname = Operatorname;
				
			item.Operatordate = Operatordate;
				
			item.Prenodeid = Prenodeid;
				
			item.Currentnodeid = Currentnodeid;
				
			item.Opinion = Opinion;
				
			item.Operatordepart = Operatordepart;
				
			item.Acceptdate = Acceptdate;
				
	        item.Save(UserName);
	    }
    }
}
