using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
	/// <summary>
	/// Strongly-typed collection for the Role class.
	/// </summary>
    [Serializable]
	public partial class RoleCollection : ActiveList<Role, RoleCollection>
	{	   
		public RoleCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>RoleCollection</returns>
		public RoleCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                Role o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the role table.
	/// </summary>
	[Serializable]
	public partial class Role : ActiveRecord<Role>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public Role()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public Role(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public Role(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public Role(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("role", TableType.Table, DataService.GetInstance("Yannis_DAO"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "id";
				colvarId.DataType = DbType.Int32;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = true;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarLimitid = new TableSchema.TableColumn(schema);
				colvarLimitid.ColumnName = "limitid";
				colvarLimitid.DataType = DbType.String;
				colvarLimitid.MaxLength = 50;
				colvarLimitid.AutoIncrement = false;
				colvarLimitid.IsNullable = true;
				colvarLimitid.IsPrimaryKey = false;
				colvarLimitid.IsForeignKey = false;
				colvarLimitid.IsReadOnly = false;
				colvarLimitid.DefaultSetting = @"";
				colvarLimitid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLimitid);
				
				TableSchema.TableColumn colvarRolename = new TableSchema.TableColumn(schema);
				colvarRolename.ColumnName = "rolename";
				colvarRolename.DataType = DbType.String;
				colvarRolename.MaxLength = 50;
				colvarRolename.AutoIncrement = false;
				colvarRolename.IsNullable = true;
				colvarRolename.IsPrimaryKey = false;
				colvarRolename.IsForeignKey = false;
				colvarRolename.IsReadOnly = false;
				colvarRolename.DefaultSetting = @"";
				colvarRolename.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRolename);
				
				TableSchema.TableColumn colvarRolecode = new TableSchema.TableColumn(schema);
				colvarRolecode.ColumnName = "rolecode";
				colvarRolecode.DataType = DbType.String;
				colvarRolecode.MaxLength = 50;
				colvarRolecode.AutoIncrement = false;
				colvarRolecode.IsNullable = true;
				colvarRolecode.IsPrimaryKey = false;
				colvarRolecode.IsForeignKey = false;
				colvarRolecode.IsReadOnly = false;
				colvarRolecode.DefaultSetting = @"";
				colvarRolecode.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRolecode);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Yannis_DAO"].AddSchema("role",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public int Id 
		{
			get { return GetColumnValue<int>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Limitid")]
		[Bindable(true)]
		public string Limitid 
		{
			get { return GetColumnValue<string>(Columns.Limitid); }
			set { SetColumnValue(Columns.Limitid, value); }
		}
		  
		[XmlAttribute("Rolename")]
		[Bindable(true)]
		public string Rolename 
		{
			get { return GetColumnValue<string>(Columns.Rolename); }
			set { SetColumnValue(Columns.Rolename, value); }
		}
		  
		[XmlAttribute("Rolecode")]
		[Bindable(true)]
		public string Rolecode 
		{
			get { return GetColumnValue<string>(Columns.Rolecode); }
			set { SetColumnValue(Columns.Rolecode, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varLimitid,string varRolename,string varRolecode)
		{
			Role item = new Role();
			
			item.Limitid = varLimitid;
			
			item.Rolename = varRolename;
			
			item.Rolecode = varRolecode;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varId,string varLimitid,string varRolename,string varRolecode)
		{
			Role item = new Role();
			
				item.Id = varId;
			
				item.Limitid = varLimitid;
			
				item.Rolename = varRolename;
			
				item.Rolecode = varRolecode;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn LimitidColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn RolenameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn RolecodeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"id";
			 public static string Limitid = @"limitid";
			 public static string Rolename = @"rolename";
			 public static string Rolecode = @"rolecode";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
