using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for s_street
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SStreetController
    {
        // Preload our schema..
        SStreet thisSchemaLoad = new SStreet();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SStreetCollection FetchAll()
        {
            SStreetCollection coll = new SStreetCollection();
            Query qry = new Query(SStreet.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SStreetCollection FetchByID(object Streetcode)
        {
            SStreetCollection coll = new SStreetCollection().Where("streetcode", Streetcode).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SStreetCollection FetchByQuery(Query qry)
        {
            SStreetCollection coll = new SStreetCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Streetcode)
        {
            return (SStreet.Delete(Streetcode) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Streetcode)
        {
            return (SStreet.Destroy(Streetcode) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int Streetcode,int? Areacode,string Streetname,decimal? Population,decimal? Area,string Memo,int? Xh)
	    {
		    SStreet item = new SStreet();
		    
            item.Streetcode = Streetcode;
            
            item.Areacode = Areacode;
            
            item.Streetname = Streetname;
            
            item.Population = Population;
            
            item.Area = Area;
            
            item.Memo = Memo;
            
            item.Xh = Xh;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int Streetcode,int? Areacode,string Streetname,decimal? Population,decimal? Area,string Memo,int? Xh)
	    {
		    SStreet item = new SStreet();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Streetcode = Streetcode;
				
			item.Areacode = Areacode;
				
			item.Streetname = Streetname;
				
			item.Population = Population;
				
			item.Area = Area;
				
			item.Memo = Memo;
				
			item.Xh = Xh;
				
	        item.Save(UserName);
	    }
    }
}
