using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Yannis.DAO
{
    /// <summary>
    /// Controller class for sys_log
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SysLogController
    {
        // Preload our schema..
        SysLog thisSchemaLoad = new SysLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SysLogCollection FetchAll()
        {
            SysLogCollection coll = new SysLogCollection();
            Query qry = new Query(SysLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysLogCollection FetchByID(object Id)
        {
            SysLogCollection coll = new SysLogCollection().Where("id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SysLogCollection FetchByQuery(Query qry)
        {
            SysLogCollection coll = new SysLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (SysLog.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (SysLog.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? Userid,string Loginname,string Ip,string Actionname,DateTime? CuDate)
	    {
		    SysLog item = new SysLog();
		    
            item.Userid = Userid;
            
            item.Loginname = Loginname;
            
            item.Ip = Ip;
            
            item.Actionname = Actionname;
            
            item.CuDate = CuDate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,int? Userid,string Loginname,string Ip,string Actionname,DateTime? CuDate)
	    {
		    SysLog item = new SysLog();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Userid = Userid;
				
			item.Loginname = Loginname;
				
			item.Ip = Ip;
				
			item.Actionname = Actionname;
				
			item.CuDate = CuDate;
				
	        item.Save(UserName);
	    }
    }
}
